### ISSUE TITLE
404 Problem

### ISSUE THREAD

**Issue by ArArgon** [imbiansl/imbiansl.github.io#33]
1. The site cannot be reached via `https://imbiansl.space` for some reasons.
2. Some pages cannot be opened, which redirect to 404 page (eg. `http://imbiansl.space/all-posts`.)

**Comment by imbiansl** [comment]
I’m now hosting my site on Coding Pages, which responds faster in mainland China. Contents on Github Pages are no longer updated. You’re welcome to visit my new site at [https://imbiansl.coding.me](https://imbiansl.coding.me). thx :)
